### ISSUE TITLE
banana jack to 3.5mm jack

### ISSUE THREAD

**Issue by dasmasdas** [elkayem/midi2cv#1]
I want to use this with 3.5mm jack but i want to make sure that I do. So can I replace it with 3.5mm jack in without changing anything?

**Comment by elkayem** [comment]
Yes, you can do this.  In fact, this is a good way to connect the grounds if your midi to cv has a different power supply than whatever it is driving.

**Comment by elkayem** [comment]
One more consideration...   With a 3.5mm jack, you will temporarily short the op amp output as you plug it in.  Some people like to put a current limiting resistor on the output to protect against this.   It isn't necessarily though if using the LM324 op amp, as the data sheet says the outputs can be shorted to ground indefinitely.   I might just go ahead and modify the schematic anyway, just to make it clear.

**Comment by dasmasdas** [comment]
Thank you so much for this incredibly good information. I dont want to waste your time , its not necessary but if you have free time modify schematic but you dont have free time no problem. Thank you
