### ISSUE TITLE
Adapting the Project for 6-Voice Polyphony

### ISSUE THREAD

**Issue by orchestron** [elkayem/midi2cv#10]
Hi,

Great project.  How would you recommend adapting the code and schematics for 6-voice polyphony?

Cheers.

**Comment by MoxorTheOne** [comment]
Im trying to do the same, or at least 4 voices, do you have a fork?

**Comment by elkayem** [comment]
Just catching up on this old issues. You would need to have multiple channels and multiple DAC outputs. Take a look at my code [here](https://github.com/elkayem/usbMIDI2CV_MC), which outputs 3 channels.
