### ISSUE TITLE
Pitch changes to Note output

### ISSUE THREAD

**Issue by GarryGNsk** [elkayem/midi2cv#11]
Hi From Siberia. I made this Project and its work great with my USSR POLIVOX SYNTH.
Is it possible to make code changes that makes pitch changes sand to note output?
when I turn pichwheel my note goes up ar down on 2 semitones.
Sorry for my English
Thanks.

**Comment by elkayem** [comment]
You could add the note and the pitch bend together if that is what you want. Closing this one, since this isn't an issue with my code so much as a feature request.
