### ISSUE TITLE
Protoboard component placement

### ISSUE THREAD

**Issue by philippejadin** [elkayem/midi2cv#12]
Thank you for this great project. By any chance, do you have the protoboard component placement?
Or a fritzing schema?
If not I'll try to make it and I will make a pull request.

**Comment by elkayem** [comment]
No I don’t. There aren’t many components and fairly straight forward to lay out, so I didn’t bother.  If you do create something I can merge.

**Comment by philippejadin** [comment]
and of course someone already made one, it is here and seems decent : https://www.reddit.com/r/synthdiy/comments/cqpecf/finally_an_updated_midicv_layout/

**Comment by elkayem** [comment]
Very interesting, thank you for the link! I am a little reluctant to post this stripboard layout on this page as the author states "however I have not tested the other other outputs as of yet so cannot verify these." However, the link is here and should help others seeking guidance on a layout.
