### ISSUE TITLE
optocoupler alternatives

### ISSUE THREAD

**Issue by otivlasc** [elkayem/midi2cv#14]
I wanted to ask some advice as I'm having difficulty getting this up and running:

I've used a TLP785 instead of the SFH618 for the optocoupler, so my first thought is that that is the issue - I'm having a hard time understanding if the TLP785 is too slow for this application.

Here are the switching characteristics from the datasheet:

<img width="643" alt="Screen Shot 2020-02-11 at 12 27 01 PM" src="https://user-images.githubusercontent.com/60910082/74211183-b8c0c500-4cc9-11ea-86b9-094024672ef5.png">

What do you think? It's a bit difficult to find this SFH618 where I am, do you know any alternatives that could definitely work? 

Thanks so much!

**Comment by ravique** [comment]
I used 6N138 for similar project (midi chorder, that recieves one midi note and sends three to the output). Overall latency was adequate.
I will try to implement this project on 6N138 too. I will try to measure the latency.
