### ISSUE TITLE
errors compiling

### ISSUE THREAD

**Issue by nickademus420** [elkayem/midi2cv#16]
Hi. I just tried to compile the code and got a ton of errors. Not sure what files or info you would need to help me, but if you can help, please let me know what info you need. Thanks.

**Comment by elkayem** [comment]
You are probably using a newer version of the MIDI and SPI libraries than I used. I haven’t tried compiling in 2 years so I’m sure there have been some changes. I should probably take a look at some point. In the mean time, you can always try a version of those libraries from mid-2018.

**Comment by nickademus420** [comment]
Thanks for the reply. Somehow during the downloading of the files something got messed up on the .ino file. I simply copied the code off the website and replaced it in the file, compiled, and uploaded! Sorry to bother you, and thank you so much for your work! Now tomorrow I test my hardware to see if it works!Will MillerSent from Mail for Windows 10 From: Larry McGovernSent: Sunday, January 24, 2021 11:26 PMTo: elkayem/midi2cvCc: nickademus420; AuthorSubject: Re: [elkayem/midi2cv] errors compiling (#16) You are probably using a newer version of the MIDI and SPI libraries than I used. I haven’t tried compiling in 2 years so I’m sure there have been some changes. I should probably take a look at some point. In the mean time, you can always try a version of those libraries from mid-2018. > On Jan 24, 2021, at 5:16 PM, nickademus420 <notifications@github.com> wrote:> > ﻿> Hi. I just tried to compile the code and got a ton of errors. Not sure what files or info you would need to help me, but if you can help, please let me know what info you need. Thanks.> > —> You are receiving this because you are subscribed to this thread.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by brbrr** [comment]
Hi @elkayem 
It is compiling in my case, but for some reason arduino is not reacting on midi input. When I comment out SPI.begin it start registering inputs. Any idea what might be wrong?
