### ISSUE TITLE
missing digital out on 11 ?

### ISSUE THREAD

**Issue by ericbalcon** [elkayem/midi2cv#17]
Hi, I'm just looking at  your schematics and noticed that D11 is connected to the MCPs, but in your code I can't see where the digital 11 is programmed. all the others it's clear but this one ? did I miss something  ? regards

**Comment by elkayem** [comment]
It’s the SPI data pin.

**Comment by ericbalcon** [comment]
Thanks for your reply . Yes, I had a look to the MCPs datasheet but I was asking why you didn't declare the output 11 in your code.
