### ISSUE TITLE
clock starting in between beats

### ISSUE THREAD

**Issue by schmynth** [elkayem/midi2cv#3]
I experienced a glitch when starting the clock of a DAW, the Midi2CV module sometimes started a clock cycle somewhat in between to quarter notes. I thought this might be happening because of the clock_count not being reset when stopping the Midi_in Clock signal. A timeout variable solved this for me by editing the case midi::Clock Block as follows:

      case midi::Clock:
        if (millis() > timeout + 300) //prevents Clock from starting in between quarter Notes!
        {
          clock_count = 0;
        }
        timeout = millis();
        if (clock_count == 0) {
        // Start clock pulse
        digitalWrite(CLOCK,HIGH);
        clock_timer=millis();    
        }
        clock_count++;
        if (clock_count == 12) {  // MIDI timing clock sends 24 pulses per quarter note.  send pulse every 12 pulses
          clock_count = 0;  
        }
      case midi::ActiveSensing: 
        break;
      default:
        d1 = MIDI.getData1();
        d2 = MIDI.getData2();
    }
    t = millis();
  }

**Comment by schmynth** [comment]
I am new to github, so if I submitted this at the wrong place or in an odd way, please tell me, thanks!

**Comment by elkayem** [comment]
Clever, thanks!   I agree, this will resync the clock pulses if they stop, for example, when restarting your DAW.  I will fold in this improvement when I get a moment.

**Comment by elkayem** [comment]
I just added your change.  Good suggestion!  I'm closing this issue.
