### ISSUE TITLE
midi2cv.sch is corrupt

### ISSUE THREAD

**Issue by davidcool** [elkayem/midi2cv#4]
Hello!
First, I LOVE this project... When I downloaded a clone the midi2cv.sch Eagle file was corrupt. Is it possible to update w/ a fixed version? Did you ever create a PCB for this?

**Comment by davidcool** [comment]
I updated to newest Eagle version and this problem was fixed!

**Comment by elkayem** [comment]
Glad you figured this out!   Also, to answer your first question, I did not create a PCs for this.  The circuit is simple enough that I just soldered it to a strip board.
