### ISSUE TITLE
Solder Arduino Outputs directly to CV Ins

### ISSUE THREAD

**Issue by BLACKAVID** [elkayem/midi2cv#5]
Yo I just found your project here!
Firstly thank you for this amazing code & instruction.
I'm also building a MFOS. Do you need to use these CV Outputs from your Panel to make a connection to the desired CV input on the "main panel"?
I would rather make it with some On/ Off switches to activate/ deactivate the function to the soldered CV Inputs. Because the labels you made on your own Panel seem to only be connected to one certain Type of CV-Input. For that you could also solder it right on the CV right or am I wrong?

Greetz

**Comment by elkayem** [comment]
Sorry, Just saw this note even though it is months old. Yes, you can solder internally and use switches as you suggest.  Just make sure your circuit and the MFOS share a common ground.
