### ISSUE TITLE
1K resistors on gate outputs

### ISSUE THREAD

**Issue by aluedt** [elkayem/midi2cv#7]
Hi,

thanks for this nice project. Just a simple question from a beginner. Why these 1K resistors on the gate outputs? Shouldn't these be 5V anyway?

Thanks
--Andree

**Comment by mikenye** [comment]
Likely for current limiting. If the outputs are accidentally shorted to ground, the 1K resistor protects the circuit from overload and damage.

**Comment by elkayem** [comment]
Sorry for the delay, closing old issues. The 1K resistors are indeed to protect against excessive current.
