### ISSUE TITLE
midi2cv with protools

### ISSUE THREAD

**Issue by nickmina** [elkayem/midi2cv#8]
I successfully made the midi2cv with arduino nano and works perfectly with my Arturia KeyLab61 master keyboard but connected to a midi interface controlled by Protools does not work.
Do you have any suggestions?
Thank you.
Nicola

**Comment by CharlesV55** [comment]
Hi,
please describe your installation:
which version of Protools/OSX
which Midi interface do you use between PT and Midi2CV
Which equipement do you drive with Mid2CV
Can you monitor Midi output (led or something)
Maybe Ptools Midi protocol is different from standard Midi. Check!

----- Mail original -----
De: "nickmina" <notifications@github.com>
À: "elkayem/midi2cv" <midi2cv@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Lundi 19 Août 2019 12:20:59
Objet: [elkayem/midi2cv] midi2cv with protools (#8)



I successfully made the midi2cv with arduino nano and works perfectly with my Arturia KeyLab61 master keyboard but connected to a midi interface controlled by Protools does not work. 
Do you have any suggestions? 
Thank you. 
Nicola

**Comment by nickmina** [comment]
Hi,
the version of Protools is the latest 2019.6.0.
I tried the midi interface integrated into the RME Fireface 400 sound card and the Roland UM-2ex midi interface and the result is the same.
I inserted a led on the midi input of the mi2cv to check the activity and everything seems to work.
Thanks

**Comment by nickmina** [comment]
I meant "the midi entry seems to work"

**Comment by nickmina** [comment]
Hi,
I solved the problem!
It was enough to replace the 6FH618A-2 optocoupler with a more performing model like the 6N138 and it all worked out.
Thanks

**Comment by elkayem** [comment]
Glad issue was solved, closing this issue.
